%R2 = CancelRotation(R_estimated);
R2 = CreateRotation(pi/2, 0, pi/9);
Q = locs';
%[Q Qmean] = MeanNormalize(Q1);
s2 = [1 0 0; 0 1 0];
q_img_2 = s2*R2*Q;
q_img_2 = q_img_2 + repmat(t_estimated, 1, size(q_img_2, 2));
[I, I2] = DebugProjectedImage(im, pixel_interp, q_img_2);
figure;
imshow(I2);
